#!/usr/bin/env julia
"""
source_rates.jl — Compute annual gamma rates from pre-computed flux tables.

Reads flux results generated by run_source_flux.jl (one subdirectory per
source/decay combination) and combines with activity data from the detector
JSON to compute absolute background rates.

Expected directory structure:
    results_dir/
    ├── ICV_barrel_Bi214/
    │   └── summary.txt
    ├── ICV_barrel_Tl208/
    │   └── summary.txt
    └── ...

Subdirectory names must be {volume_name}_{decay_type}/.

Usage:
    julia --project=.. scripts/source_rates.jl --results-dir results/
    julia --project=.. scripts/source_rates.jl --results-dir results/ --detector ../data/detector_lz.json
"""

using ArgParse
using LXeMC
using Printf
using JSON

const SECONDS_PER_YEAR = 3.156e7

function parse_args()
    s = ArgParseSettings(
        description = "Compute annual gamma rates from flux tables + activities",
        version = "0.1.0",
        add_version = true
    )

    @add_arg_table! s begin
        "--results-dir", "-r"
            help = "Directory containing flux result subdirectories"
            arg_type = String
            required = true
        "--detector", "-d"
            help = "Path to detector JSON"
            arg_type = String
            default = ""
        "--output", "-o"
            help = "Output CSV path (default: rates.csv in results-dir)"
            arg_type = String
            default = ""
    end

    return ArgParse.parse_args(s)
end


function read_survival_fraction(summary_path::String)::Union{Float64,Nothing}
    isfile(summary_path) || return nothing
    for line in eachline(summary_path)
        if occursin("Total survival prob:", line)
            m = match(r"([\d.]+e[+-]?\d+)", line)
            m !== nothing && return parse(Float64, m.match)
        end
        # Legacy format: "Surviving: N (X.XXXX%)"
        if occursin("Surviving:", line) && occursin("%", line)
            m = match(r"\(([\d.]+)%\)", line)
            if m !== nothing
                return parse(Float64, m.captures[1]) / 100.0
            end
        end
    end
    nothing
end


function load_activities(det_path::String)::Dict{String,Dict{String,Float64}}
    """Load activity data from detector JSON. Returns volume_name -> {Bi214: mBq/kg, Tl208: mBq/kg}."""
    raw = open(det_path, "r") do io
        JSON.parse(io)
    end
    activities = Dict{String,Dict{String,Float64}}()
    for vd in raw["volumes"]
        name = vd["name"]
        a_bi = get(vd, "A_Bi214_mBq_per_kg", nothing)
        a_tl = get(vd, "A_Tl208_mBq_per_kg", nothing)
        if a_bi !== nothing || a_tl !== nothing
            activities[name] = Dict{String,Float64}()
            a_bi !== nothing && (activities[name]["Bi214"] = Float64(a_bi))
            a_tl !== nothing && (activities[name]["Tl208"] = Float64(a_tl))
        end
    end
    activities
end


function main()
    args = parse_args()

    results_dir = args["results-dir"]
    det_path = args["detector"]
    if isempty(det_path)
        det_path = default_detector_path()
    end
    out_path = args["output"]
    if isempty(out_path)
        out_path = joinpath(results_dir, "rates.csv")
    end

    # Load detector for masses and activities
    cfg = default_config()
    mats = load_materials(cfg)
    det = load_detector(det_path, mats)
    by_name = Dict(v.name => v for v in det.volumes)

    # Load activity data from JSON
    activities = load_activities(det_path)

    # Load decay schemes for BR
    decays = load_decays()

    # Scan results directory for subdirectories
    println("=" ^ 80)
    println("Source Rates Summary")
    println("=" ^ 80)
    @printf("%-20s %-8s %8s %10s %12s %10s %12s\n",
            "Volume", "Decay", "Mass[kg]", "A[mBq/kg]", "decays/yr", "surv_frac", "γ_to_LXe/yr")
    println("-" ^ 80)

    rows = Vector{String}()
    push!(rows, "volume,decay,mass_kg,A_mBq_per_kg,decays_per_yr,survival_fraction,gammas_to_LXe_per_yr")

    total_bi = 0.0
    total_tl = 0.0

    for entry in readdir(results_dir)
        subdir = joinpath(results_dir, entry)
        isdir(subdir) || continue

        # Parse subdirectory name: {volume}_{decay}
        parts = rsplit(entry, "_", limit=2)
        length(parts) == 2 || continue
        vol_name, decay_name = parts[1], parts[2]

        # Check we have this volume
        haskey(by_name, vol_name) || continue
        haskey(activities, vol_name) || continue
        haskey(decays, decay_name) || continue

        act_dict = activities[vol_name]
        haskey(act_dict, decay_name) || continue

        # Read survival fraction from summary
        summary_path = joinpath(subdir, "summary.txt")
        surv = read_survival_fraction(summary_path)
        surv === nothing && continue

        # Compute rate
        vol = by_name[vol_name]
        mass_kg = mass(vol) / 1000.0
        A_mBq = act_dict[decay_name]
        A_Bq = A_mBq * 1e-3
        BR = decays[decay_name].BR_from_chain
        decays_per_yr = A_Bq * mass_kg * BR * SECONDS_PER_YEAR
        gammas_per_yr = decays_per_yr * surv

        @printf("%-20s %-8s %8.1f %10.3f %12.1f %10.4e %12.1f\n",
                vol_name, decay_name, mass_kg, A_mBq, decays_per_yr, surv, gammas_per_yr)

        push!(rows, @sprintf("%s,%s,%.1f,%.3f,%.1f,%.4e,%.1f",
              vol_name, decay_name, mass_kg, A_mBq, decays_per_yr, surv, gammas_per_yr))

        if decay_name == "Bi214"
            total_bi += gammas_per_yr
        else
            total_tl += gammas_per_yr
        end
    end

    println("-" ^ 80)
    @printf("%-20s %-8s %8s %10s %12s %10s %12.1f\n",
            "TOTAL", "Bi214", "", "", "", "", total_bi)
    @printf("%-20s %-8s %8s %10s %12s %10s %12.1f\n",
            "TOTAL", "Tl208", "", "", "", "", total_tl)
    @printf("%-20s %-8s %8s %10s %12s %10s %12.1f\n",
            "TOTAL", "all", "", "", "", "", total_bi + total_tl)
    println("=" ^ 80)

    # Write CSV
    open(out_path, "w") do io
        for row in rows
            println(io, row)
        end
    end
    println("\nSaved: $out_path")
end

main()
